name: Django + Playwright UI Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m venv env
          source env/bin/activate
          pip install -r requirements.txt
          playwright install --with-deps

      - name: Run Django migrations
        run: |
          source env/bin/activate
          python manage.py migrate

      - name: Start Django server in background
        run: |
          source env/bin/activate
          nohup python manage.py runserver 0.0.0.0:8000 &

      - name: Wait for server to start
        run: sleep 5

      - name: Run Playwright tests
        run: |
          source env/bin/activate
          pytest -s ui_tests/test_home.py